### ISSUE TITLE
Not compatible with Minio?

### ISSUE THREAD

**Issue by madchap** [camptocamp/bivac#199]
Hi,

I installed minio server (https://minio.io/) on my home machine, which provides a S3 compatible API.

However, I could not make it work with bivac. It does not seem to detect the backend:

```
DEBU[0036] Creating container                            command="-r s3+http://helmsdeep.home:9001/docker-backups/9a89daa61c64/grafana_varlog snapshots --no-cache" environment="AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxx, AWS_SECRET_ACCESS_KEY=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy, OS_USERNAME=, OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=, OS_REGION_NAME=, RESTIC_PASSWORD=" image="restic/restic:latest"
DEBU[0036] Launching with '-r s3+http://helmsdeep.home:9001/docker-backups/9a89daa61c64/grafana_varlog snapshots --no-cache'...
DEBU[0037]  Fatal: parsing repository location failed: invalid backend
If the repo is in a local directory, you need to add a `local:` prefix
```

Before I dig any further, does anyone have any successful experience using bivac with minio server?

Thank you.

**Comment by mcanevet** [comment]
@madchap it should be. Maybe the URL you are passing is not correct for the engine you are using. If you are using the Restic engine (default), then your url should look like that : https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#minio-server
Could you try with `s3:http://helmsdeep.home:9001/docker-backups`?

**Comment by madchap** [comment]
Thank you @mcanevet. I am hitting another (dns) issue now, but I am fairly sure that this is it. Maybe a suggestion to adapt the examples given on the front page to this URL scheme, since Restic is the default engine? Would that make sense?

**Comment by madchap** [comment]
Hi,

Sorry for re-opening, but while the url thing was indeed right -- and after fixing my intra-container DNS issues, it seems that bivac is just hanging while eating CPU away.

debug out is not very talkative, however.

```
DEBU[0001] Creating container command="-r s3:http://helmsdeep.home:9001/docker-backups/eebb9518eb28/mc_data snapshots --no-cache" environment="OS_REGION_NAME=, RESTIC_PASSWORD=, AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxx, AWS_SECRET_ACCESS_KEY=yyyyyyyyyyyyyyyyyyyyy, OS_USERNAME=, OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=" image="restic/restic:latest"
DEBU[0001] Launching with '-r s3:http://helmsdeep.home:9001/docker-backups/eebb9518eb28/mc_data snapshots --no-cache'... 
DEBU[0002]  Fatal: unable to open config file: Stat: The specified key does not exist.
 Is there a repository at the following location?
 s3:http://helmsdeep.home:9001/docker-backups/eebb9518eb28/mc_data
 
DEBU[0002] Removing container                            container=7de0d472638385b3f97513a59918a7dcfd656b6f53eef4e4ac5ba34a3a9ec005
DEBU[0002] Image already pulled, not pulling             image="restic/restic:latest"
DEBU[0002] Creating container                            command="-r s3:http://helmsdeep.home:9001/docker-backups/eebb9518eb28/mc_data init --no-cache" environment="OS_REGION_NAME=, RESTIC_PASSWORD=, AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxx, AWS_SECRET_ACCESS_KEY=yyyyyyyyyyyyyyyyyyyyyyyyyy, OS_USERNAME=, OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=" image="restic/restic:latest"
DEBU[0002] Launching with '-r s3:http://helmsdeep.home:9001/docker-backups/eebb9518eb28/mc_data init --no-cache'...
```

Been sitting there for 15mn now, there is less than 1MB in that volume.
CPU is cumulating up of 90% CPU across all cores available, and dockerd around 50% when that happens.

There is no log at all in the restic container that is launched by bivac. The restic container also resolves well and can contact minio. I have not attempted yet to debug restic.

Thanks for your guidance.
Cheers,
fred

**Comment by mcanevet** [comment]
@madchap we are also using Minio internaly but we can't reproduce. It works fine for us...
We are going to try to get the workers logs in the manager to ease the debug.

**Comment by cryptobioz** [comment]
@madchap: Did you provide a password for Restic? It looks like the variable `RESTIC_PASSWORD` is empty.

**Comment by madchap** [comment]
@cryptobioz indeed. I will try.. I see the README.md was updated 3 hours ago with that information. Cheers.

**Comment by madchap** [comment]
So, now a panic error :-)

```
DEBU[0004] Creating container                            command="-r s3:http://helmsdeep.home:9001/docker-backups/1cc2bfaaebdb/mc_data init --no-cache" environment="OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=, OS_REGION_NAME=, RESTIC_PASSWORD=xxxxxxxx, AWS_ACCESS_KEY_ID=yyyyyyyyyy, AWS_SECRET_ACCESS_KEY=zzzzzzzzzzzzzzzzzzzz, OS_USERNAME=" image="restic/restic:latest"
DEBU[0004] Launching with '-r s3:http://helmsdeep.home:9001/docker-backups/1cc2bfaaebdb/mc_data init --no-cache'... 
DEBU[0007]  created restic repository 71cbd5eb38 at s3:http://helmsdeep.home:9001/docker-backups/1cc2bfaaebdb/mc_data
 
 Please note that knowledge of your password is required to access
 the repository. Losing your password means that your data is
 irrecoverably lost.
 
DEBU[0007] Removing container                            container=6e2b118e07e5488f67c86aeabe1b0f5c58bd1c9e43b4a1163766f6802e87c74e
DEBU[0008] Image already pulled, not pulling             image="restic/restic:latest"
DEBU[0008] Creating container                            command="--hostname 1cc2bfaaebdb -r s3:http://helmsdeep.home:9001/docker-backups/1cc2bfaaebdb/mc_data backup /var/lib/docker/volumes/mc_data/_data/ --no-cache" environment="OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=, OS_REGION_NAME=, RESTIC_PASSWORD=xxxxxxxxxxx, AWS_ACCESS_KEY_ID=yyyyyyyyyyyyyyyyyyyyyyy, AWS_SECRET_ACCESS_KEY=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz, OS_USERNAME=" image="restic/restic:latest"
DEBU[0008] Launching with '--hostname 1cc2bfaaebdb -r s3:http://helmsdeep.home:9001/docker-backups/1cc2bfaaebdb/mc_data backup /var/lib/docker/volumes/mc_data/_data/ --no-cache'... 
DEBU[0010]  repository 71cbd5eb opened successfully, password is correct
 panic: runtime error: slice bounds out of range
 
 goroutine 6 [running]:
 github.com/restic/restic/internal/ui/termstatus.(*Terminal).SetStatus(0xc4200769c0, 0xc4200973d0, 0x1, 0x1)
 	src/github.com/restic/restic/internal/ui/termstatus/status.go:310 +0x319
 github.com/restic/restic/internal/ui.(*Backup).update(0xc420241a00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420300d00, 0x0)
 	src/github.com/restic/restic/internal/ui/backup.go:181 +0x69e
 github.com/restic/restic/internal/ui.(*Backup).Run(0xc420241a00, 0xc06fa0, 0xc4200b2f40, 0x0, 0x0)
 	src/github.com/restic/restic/internal/ui/backup.go:139 +0x5d5
 main.runBackup.func2(0x0, 0x0)
 	src/github.com/restic/restic/cmd/restic/cmd_backup.go:360 +0x75
 github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc4202305a0, 0xc4202931a0)
 	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
 created by github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
 	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb9

```

**Comment by madchap** [comment]
I pulled today the latest restic docker image, and all is fine.

Therefore, I guess the only thing "buggy" relates to just give the documentation a little love (which in this case it was enough to add the restic bit for the password).

I am closing this for now.

Thanks!

**Comment by madchap** [comment]
Well, not quite I guess, but that's for another time ;-)

```
ERRO[0255] Failed to backup volume blog_mariadb_data: failed to backup volume: failed to backup the volume: after 3 attempts, last error: Restic exited with state 1 while backuping the volume
```
