### ISSUE TITLE
Backup is failing after a fresh docker install (crash and no-ending)

### ISSUE THREAD

**Issue by soullivaneuh** [camptocamp/bivac#335]
After a fresh docker installation, I tried to run the agent without any luck:

```
❯ dce app bivac agent
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/camptocamp/bivac/cmd/agent.glob..func1(0x22574c0, 0x2282f38, 0x0, 0x0)
        /go/src/github.com/camptocamp/bivac/cmd/agent/agent.go:23 +0x180
github.com/spf13/cobra.(*Command).execute(0x22574c0, 0x2282f38, 0x0, 0x0, 0x22574c0, 0x2282f38)
        /go/src/github.com/camptocamp/bivac/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x2257260, 0xc0004fff58, 0x11f1e6a, 0x2257260)
        /go/src/github.com/camptocamp/bivac/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/camptocamp/bivac/vendor/github.com/spf13/cobra/command.go:800
github.com/camptocamp/bivac/cmd.Execute(0x16c2ea0, 0x5, 0x16c51b8, 0xa, 0x16fc4c0, 0x28, 0x1506912, 0x9)
        /go/src/github.com/camptocamp/bivac/cmd/cmd.go:57 +0x75
main.main()
        /go/src/github.com/camptocamp/bivac/main.go:26 +0xef
```

Then, I try to backup a random volume manually:

```
❯ dce app bivac backup fusionauth_fa_config
Backing up `fusionauth_fa_config'...
```

The command keep running like that without any end.

Is it a bug or maybe I'm missing something?

**Comment by cryptobioz** [comment]
Hello @soullivaneuh, sorry for the delay.

Is your problem still occurs? If so, could you please share with us what release of Bivac you're using and how you configured it?
